require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ReadsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Read. As you add validations to Read, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all reads as @reads" do
      read = Read.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:reads)).to eq([read])
    end
  end

  describe "GET #show" do
    it "assigns the requested read as @read" do
      read = Read.create! valid_attributes
      get :show, params: {id: read.to_param}, session: valid_session
      expect(assigns(:read)).to eq(read)
    end
  end

  describe "GET #new" do
    it "assigns a new read as @read" do
      get :new, params: {}, session: valid_session
      expect(assigns(:read)).to be_a_new(Read)
    end
  end

  describe "GET #edit" do
    it "assigns the requested read as @read" do
      read = Read.create! valid_attributes
      get :edit, params: {id: read.to_param}, session: valid_session
      expect(assigns(:read)).to eq(read)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Read" do
        expect {
          post :create, params: {read: valid_attributes}, session: valid_session
        }.to change(Read, :count).by(1)
      end

      it "assigns a newly created read as @read" do
        post :create, params: {read: valid_attributes}, session: valid_session
        expect(assigns(:read)).to be_a(Read)
        expect(assigns(:read)).to be_persisted
      end

      it "redirects to the created read" do
        post :create, params: {read: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Read.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved read as @read" do
        post :create, params: {read: invalid_attributes}, session: valid_session
        expect(assigns(:read)).to be_a_new(Read)
      end

      it "re-renders the 'new' template" do
        post :create, params: {read: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested read" do
        read = Read.create! valid_attributes
        put :update, params: {id: read.to_param, read: new_attributes}, session: valid_session
        read.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested read as @read" do
        read = Read.create! valid_attributes
        put :update, params: {id: read.to_param, read: valid_attributes}, session: valid_session
        expect(assigns(:read)).to eq(read)
      end

      it "redirects to the read" do
        read = Read.create! valid_attributes
        put :update, params: {id: read.to_param, read: valid_attributes}, session: valid_session
        expect(response).to redirect_to(read)
      end
    end

    context "with invalid params" do
      it "assigns the read as @read" do
        read = Read.create! valid_attributes
        put :update, params: {id: read.to_param, read: invalid_attributes}, session: valid_session
        expect(assigns(:read)).to eq(read)
      end

      it "re-renders the 'edit' template" do
        read = Read.create! valid_attributes
        put :update, params: {id: read.to_param, read: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested read" do
      read = Read.create! valid_attributes
      expect {
        delete :destroy, params: {id: read.to_param}, session: valid_session
      }.to change(Read, :count).by(-1)
    end

    it "redirects to the reads list" do
      read = Read.create! valid_attributes
      delete :destroy, params: {id: read.to_param}, session: valid_session
      expect(response).to redirect_to(reads_url)
    end
  end

end
